.TH "md__scratch2_NAGAPE_epic_Gillian.Petro_UFS-UTILS-srw_sorc_sfc_climo_gen.fd_docs_README" 3 "Sun Mar 23 2025" "Version 1.11.0" "sfc_climo_gen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__scratch2_NAGAPE_epic_Gillian.Petro_UFS-UTILS-srw_sorc_sfc_climo_gen.fd_docs_README \- README 
This program creates climatological surface fields on the model grid, such as soil type and albedo\&.
.PP
Documentation may be found at https://ufs-community.github.io/UFS_UTILS 
